### ISSUE TITLE
[Bug] Update Note Link Text not working

### ISSUE THREAD

**Issue by shanapote** [windingwind/zotero-better-notes#127] opened 2022-08-26 22:26 UTC
**Describe the bug**
Attempts to update linked text in main note by clicking the 'update link text' button in the link popup _does not update_ the linked text.

**To Reproduce**
1. Modify the first line of a linked note in the preview area.
2. Go to the main note.
3. Click on the link for the linked note.
4. Click on the 'update' icon in the link popup.
5. See error, that modified text in the linked note is not updated in the linked note section of the main note.

**Expected behavior**
Modified text in the linked note would be updated in the associated linked note area of the main note.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Zotero: Version 6.0.13

**Additional context**
I can't tell if this issue has already been reported, as some of the issues are in languages I don't read. Apologies if this is a duplicate!

**Comment by windingwind** [comment] 2022-08-27 02:12
Thanks for the report. I’ll check it soon.

**Comment by windingwind** [comment] 2022-08-31 11:22
I cannot reproduce this bug on my Zotero. Could you please check if the plugin is up-to-date?

**Comment by StupidYR** [comment] 2022-09-02 04:49
UserGuide
```
3.5 Update Note Link Text
Update the link text in main note by clicking the 'update link text' button in the link popup.
```
This is what I understand the **update** means.
```
Updated link text, instead of inserted linked note's context.
```

But I'm looking forward to the latter.

**Comment by windingwind** [comment] 2022-09-02 10:13
@StupidYR Not sure what you mean, we support both.

![image](https://user-images.githubusercontent.com/33902321/188117781-36aa8adb-f40e-460a-99c5-715d74588424.png)

**Comment by StupidYR** [comment] 2022-09-02 11:12
@windingwind I'm not good at communicating in English, sorry for the inconvenience to your understanding.

[![kJ7nm.png](https://s1.328888.xyz/2022/09/02/kJ7nm.png)](https://imgloc.com/i/kJ7nm)

Zotero: Version 6.0.13，Zotero Better Notes：0.6.29

**Comment by windingwind** [comment] 2022-09-02 11:23
It doesn't work that way. The link text is the text of LINK itself, the blue text `Conclusion`.

The embeded content will not be updated. To prevent the possible inconsistancy between main note and linked note, we use links.
To preview the linked note, you don't need to embed it. Click the link or move the cursor to the link.

**Comment by StupidYR** [comment] 2022-09-02 11:26
I get it, thank you very much for your answer

**Comment by shanapote** [comment] 2022-09-02 19:07
Ah, thank you for this thread StupidYR and windingwind! I too thought that the sync function was to update the embedded text, not the link. But it makes sense that if you change the link, you would want that updated everywhere it was used!

Warmly,
Shana

--
Shana Pote
***@***.*** | 484.489.0079
Schedule with me: https://usemotion.com/meet/shana-pote/meeting
www.shanapote.com<http://www.shanapote.com>
________________________________

**Comment by windingwind** [comment] 2022-09-03 05:56
The link keeps the consistency of linked note content. After you change the linked note, you can always access the latest content of it via the link.
That's why we use links. The embed function embeds a copy of the linked note content. That's why we recommend you to keep the links and only embed the notes when exporting.

**Comment by windingwind** [comment] 2022-09-04 16:40
Hope the discussions would be helpful. If the issue is solved, I'll close it later.
Thanks you shanapote and StupidYR.

**Closed** 2022-09-10 14:07 UTC
Labels: bug
