### ISSUE TITLE
[Bug] After linking a note with Better Notes, the inserted link into 'Note Workspace' tab is truncated

### ISSUE THREAD

**Issue by ThachNgocTran** [windingwind/zotero-better-notes#905] opened 2024-03-05 21:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2 64bit
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

## Description

After linking a Note within a currently opened PDF to a Note Workspace, thanks to Better Notes plugin, the inserted link works as expected. However, it is truncated. It seems to have a max length of 120 characters.

Not sure if this is by-design, or a bug. Hope that this limitation is configurable somewhere.

## Reproducibility

1. Open a PDF file into a Tab within Zotero.
2. In this tab, highlight a text.
3. Create a new Note. Open the Note.
4. Click on the highlighted text.
5. Click on the triple dots.
6. Click on 'Add to Note'.
7. Click on Better Notes icon just above the opened Note. Link to the Note Workspace.
8. Return to the Note Workspace. The link is inserted, but it is unfortunately truncated.

### Screenshots

![1](https://github.com/windingwind/zotero-better-notes/assets/9520123/e3872686-e9c6-4b45-941d-4b257c8c1cc7)

![2](https://github.com/windingwind/zotero-better-notes/assets/9520123/dacb49f0-d677-4d8e-9054-a639e27b81aa)

### Debug Output

The Debug Output:

[Debug Output.zip](https://github.com/windingwind/zotero-better-notes/files/14501582/Debug.Output.zip)

### Anything else?

I tried creating a link with text description more than 200 characters, and got no problem. So probably this bug is not by-design by Zotero. When generating the link in Note Workspace, it got truncated beforehand.

**Comment by windingwind** [comment] 2024-03-07 01:10
The default link text is generated from `getNoteTitle`, which slices the first 120 chars of the first line of a note. So to answer your question, it's by design by Zotero, not this plugin.

You could modify the `QuickInsert` template to customize the link text, though.

This is not a bug, so I will close this issue.

**Closed by windingwind** 2024-03-07 01:10 UTC
Labels: bug

**Comment by ThachNgocTran** [comment] 2024-03-07 10:48
@windingwind You're right. This is not a bug. Thanks for the quick response. 👍

Nevertheless, to get the full text note (instead of being truncated as showed above), one needs to modify the QuickInsert template, and play with the javascript a little bit.

In Template Editor of Better Notes:

![1](https://github.com/windingwind/zotero-better-notes/assets/9520123/18cc842c-7c24-4dbb-ad41-436affcf0717)

In Note Workspace tab, the result will end up as I desired:

![2](https://github.com/windingwind/zotero-better-notes/assets/9520123/40a786c3-d8f7-43ed-80fa-1148d208f80e)

**Comment by windingwind** [comment] 2024-03-07 11:24
Cool! If you don't mind, I'd like to convert your reply to a discussion as a template share, which might be helpful to others.

**Comment by windingwind** [comment] 2024-03-07 11:27
Also, `subNoteItem.getNote()` might not work very well with embedded images. You can use the API provided by this plugin to import note content into another note, see https://github.com/windingwind/zotero-better-notes/discussions/245

**Comment by windingwind** [comment] 2024-03-07 11:27
Also, `subNoteItem.getNote()` might not work very well with embedded images. You can use the API provided by this plugin to import note content into another note, see https://github.com/windingwind/zotero-better-notes/discussions/245

**Comment by ThachNgocTran** [comment] 2024-03-07 11:40
> Cool! If you don't mind, I'd like to convert your reply to a discussion as a template share, which might be helpful to others.

Please go ahead. You're welcome.
