### ISSUE TITLE
[Bug] Mainnote exported result in empty file

### ISSUE THREAD

**Issue by FongTsang** [windingwind/zotero-better-notes#102] opened 2022-08-01 05:20 UTC
Dear developer, sorry to bother u, I try to export my current main note as an external markdown file, but the exported file is always an empty file. This issue happen only to main note exportation, other Annotation extracted directed from PDF exportation works just fine. 
Main note content and export setting
![图片](https://user-images.githubusercontent.com/53118840/182077399-dd381705-6a13-4c24-85a5-372315cf02b8.png)
The exportation result
![图片](https://user-images.githubusercontent.com/53118840/182077518-99624bcb-75f5-4153-8488-c2914baa5dfc.png)

**Comment by windingwind** [comment] 2022-08-01 07:06
Could you please describe in detail:
- Which version of the plugin are you using?
- Try to export to a new note with linked notes embedded, then export the new note to markdown. Does the blank export bug still exist?
- Please go to menu-> Help->Debug Output->View Output and then do the export. Paste the output/upload the debug file here.

**Comment by windingwind** [comment] 2022-08-02 16:04
@paulgenz 
Thanks for the debug output. Could you please paste a screenshot of the export window?

As for #104 , please select the export to MD & export linked notes to MD both to enable the auto sync. We only support auto sync under this condition.

**Comment by paulgenz** [comment] 2022-08-03 08:42
Hi, I'm not totally sure what you refer to as *export window*. I just made a gif of the export process and attached the [debug file](https://github.com/windingwind/zotero-better-notes/files/9249531/debug_output_export_paulgenz.txt) again.
![export_bug_paulgenz](https://user-images.githubusercontent.com/72145690/182564026-7e01990b-4a0b-4e1a-9cf7-787e3387bef5.gif).

Additionally: I'm using [Obsidian](https://obsidian.md) for handling notes and stuff. And also here I'm experiencing problems when using the Zotero related Obsidian-Plugins (such as [Obsidian Zotero Integration](https://github.com/mgmeyers/obsidian-zotero-integration)). So the problem is possibly related to my Zotero installation..?!

**Comment by windingwind** [comment] 2022-08-03 09:48
Considering the Linux platform you are using, it could possibly because the Zotero doesn’t have write access to the directory you selected.
Maybe you could try to make a new directory and use `sudo chmod -R 777 /your/dir` to allow anyone to write there. Then try to export to that directory and see if there are any exported files.

**Comment by FongTsang** [comment] 2022-08-03 10:36
After recreate main note and embedded the note into it again, my problem mysteriously solved. Here are my platform information:
Zotero 6.0.10
Better Notes: 0.6.12
There is the debug information:
[debug.txt](https://github.com/windingwind/zotero-better-notes/files/9250531/debug.txt)
Hope these can be helpful.

**Comment by paulgenz** [comment] 2022-08-03 11:59
> Considering the Linux platform you are using, it could possibly because the Zotero doesn’t have write access to the directory you selected. Maybe you could try to make a new directory and use `sudo chmod -R 777 /your/dir` to allow anyone to write there. Then try to export to that directory and see if there are any exported files.

I checked the permissions, which where already set for allow all.

However, I re-installed Zotero (to 6.0.9) and also better-notes (updated from 0.6.15 to 0.6.16). Now the export works again. Also, my obsidian-plugin related issue was solved.

**Comment by windingwind** [comment] 2022-08-03 14:37
@paulgenz 
Glad to know it works!

**Comment by windingwind** [comment] 2022-08-04 05:21
I’ll close this issue.

**Closed by windingwind** 2022-08-04 05:21 UTC
Labels: bug
